### ISSUE TITLE
Wheels for ARM/M1 macOS?

### ISSUE THREAD

**Issue by b-long** [opentdf/client-python#21]
### Headline

OpenTDF's Python SDK is available for:

- macOS on x86_64
- Windows on x86_64

It is not available for:

- macOS on ARM/M1 chip

### Details
Currently, ARM/M1 CPU python wheels (build artifacts) are not available on pypi.org for the latest OpenTDF version.  As a result, the developers are limited to the capabilities that are exposed in the Jun 3, 2022 Python API (version 1.0.0).
 
Many developers are using macOS with an ARM/M1 CPU architecture.  The  ARM/M1 CPU architecture was supported in the OpenTDF version 1.0.0 Python API.  See "Download files" and search for "macosx": 
 
https://pypi.org/project/opentdf/1.0.0/#files
 
However, later versions like 1.2.0 do not support ARM/M1 CPU.  See "Download files" and search for "macosx": 
https://pypi.org/project/opentdf/1.2.0/#files
 
The versions in-between 1.0.0 and 1.2.0 (1.1.6, 1.1.7, 1.1.8, and 1.1.9) also do not support ARM/M1 CPU.  Ideally, this is a helpful data point to bisect the change which resulted in no longer building ARM/M1 python wheels.
 

I have spent a few nights researching how to fix this bug, but I don't think I have the C/C++ and pybind11 knowledge [1][2] to properly solve it.
 
I’ve attached the install log output for 3 platforms (macOS ARM/M1, macOS x86, and Windows x86).
 
[1]: pybind11 is used by the client-python project to create Python bindings of existing OpenTDF C++ code.  Source: [https://github.com/opentdf/client-python/blob/main/src/python-bindings/pips/python_module.cpp](https://github.com/opentdf/client-python/blob/a1aba7434f4c37c561d44a37d4df71a15d98d51b/src/python-bindings/pips/python_module.cpp) 
[2]: More information about pybind11 is available here: https://pybind11.readthedocs.io/en/stable/ 

### Log files for different platforms

- [install-log-mac-m1.txt](https://github.com/opentdf/client-python/files/10394836/install-log-mac-m1.txt)
- [install-log-mac-x86.txt](https://github.com/opentdf/client-python/files/10394839/install-log-mac-x86.txt)
- [install-log-windows-x86.txt](https://github.com/opentdf/client-python/files/10394841/install-log-windows-x86.txt)

**Comment by sujankota** [comment]
GitHub actions did not have support for Mac M1. However, you can build the wheels on your local machine, by following these instructions.



### Install & Build

Tools required to build the tdf library and run the sample

Homebrew

`ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

Cmake

`brew install cmake`

Python3

`brew install python3`

Conan

`brew install conan`

Once all these tools are installed run `$build-all.sh` to build the tdf library and to
execute unit tests.

**Comment by cassandrabailey293** [comment]
Looks like there may be a GH action that can build them - https://github.com/pratyushmittal/fast_diff_match_patch/blob/main/.github/workflows/wheels.yml#L7-L321 

another resource: https://github.com/actions/setup-python/issues/108

**Comment by b-long** [comment]
A simple (and complete) example that may help you is here: https://github.com/pybind/python_example

**Comment by b-long** [comment]
Marking this as closed.  The latest release has several macosx / ARM wheel variants available on PyPI: https://pypi.org/project/opentdf/#files
